### ISSUE TITLE
won't start

### ISSUE THREAD

**Issue by johndpope** [BarsTiger/TeleDiffusionBot#1]
```
TOKEN='5747182005:1234'
ADMIN='1111'
DB_CHAT='-11111'
DB_PATH='.'
ENCRYPTION_KEY='12345678'

```

TELE-DIFFUSION-BOT
Traceback (most recent call last):
File "/home/oem/Documents/gitWorkspace/TeleDiffusionBot/main.py", line 23, in
asyncio.run(main())
File "/home/oem/miniconda3/envs/ldm2/lib/python3.9/asyncio/runners.py", line 44, in run
return loop.run_until_complete(main)
File "/home/oem/miniconda3/envs/ldm2/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
return future.result()
File "/home/oem/Documents/gitWorkspace/TeleDiffusionBot/main.py", line 12, in main
bot.handlers.register.register_handlers()
File "/home/oem/Documents/gitWorkspace/TeleDiffusionBot/bot/handlers/register.py", line 5, in register_handlers
from bot.handlers import (
File "/home/oem/Documents/gitWorkspace/TeleDiffusionBot/bot/handlers/txt2img/init.py", line 2, in
from .txt2img import generate_command
File "/home/oem/Documents/gitWorkspace/TeleDiffusionBot/bot/handlers/txt2img/txt2img.py", line 5, in
from bot.modules.api.txt2img import txt2img
File "/home/oem/Documents/gitWorkspace/TeleDiffusionBot/bot/modules/api/txt2img.py", line 8, in
async def txt2img(prompt: Prompt, ignore_exceptions: bool = False) -> list[bytes, dict] | None:
TypeError: unsupported operand type(s) for |: 'types.GenericAlias' and 'NoneType'

**Comment by johndpope** [comment]
pytho 3.9 issue 
https://github.com/tiangolo/typer/issues/371
