### ISSUE TITLE
Set model not working

### ISSUE THREAD

**Issue by seel2304** [BarsTiger/TeleDiffusionBot#10]
If i type to bot /config, choose Global Setting -> Set Model, i get "⏳ Loading..." and no more changing. 
If i open http://192.168.10.60:7860/docs#/default/get_sd_models_sdapi_v1_sd_models_get, and execute it, i can see a full list of my models
![image](https://user-images.githubusercontent.com/37144504/235688726-f9d7821d-fc60-4d7a-bbe5-c2bb0c55f731.png)
How to see the same list in this bot and change the models?
Steps: 
1. (terminal) python main.py
output (terminal):
TELE-DIFFUSION-BOT
All handlers registered
All callbacks registered
Commands registered
Bot will start now

2. (private telegram chat to bot) /start
output (telegram):
🔄️ Bot database synchronised because of restart. If you tried to run a command, run it again
output (terminal):
First database pulling for this instance - DB is up-to-date
3.  (private telegram chat to bot) /start
output (telegram):
👋 Hello, kilisauros. You are admin of this instance, so we will check config for you now
output (terminal): none
4. (private telegram chat to bot) /config -> Global Settings -> Set Model
output (telegram):
⏳ Loading...
output (terminal, 7 min after clicking on "Set model"): 
Task exception was never retrieved
future: <Task finished name='Task-37' coro=<Dispatcher._process_polling_updates() done, defined at /var/www/miniconda3/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=AttributeError("'CallbackQuery' object has no attribute 'message_thread_id'")>
Traceback (most recent call last):
  File "/media/bad-hdd-nextcloud/nextcloud-data/Programms/TeleDiffusionBot/bot/utils/errorable_command.py", line 22, in wrapper
    _ = await func(*args, **kwargs)
  File "/media/bad-hdd-nextcloud/nextcloud-data/Programms/TeleDiffusionBot/bot/callbacks/config/global_settings.py", line 26, in on_set_model
    models = await get_models()
  File "/media/bad-hdd-nextcloud/nextcloud-data/Programms/TeleDiffusionBot/bot/modules/api/models.py", line 11, in get_models
    return [x["title"] for x in await r.json()]
  File "/var/www/miniconda3/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1099, in json
    await self.read()
  File "/var/www/miniconda3/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1037, in read
    self._body = await self.content.read()
  File "/var/www/miniconda3/lib/python3.10/site-packages/aiohttp/streams.py", line 375, in read
    block = await self.readany()
  File "/var/www/miniconda3/lib/python3.10/site-packages/aiohttp/streams.py", line 397, in readany
    await self._wait("readany")
  File "/var/www/miniconda3/lib/python3.10/site-packages/aiohttp/streams.py", line 303, in _wait
    with self._timer:
  File "/var/www/miniconda3/lib/python3.10/site-packages/aiohttp/helpers.py", line 721, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/www/miniconda3/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/var/www/miniconda3/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "/var/www/miniconda3/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/var/www/miniconda3/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 283, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
  File "/var/www/miniconda3/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/media/bad-hdd-nextcloud/nextcloud-data/Programms/TeleDiffusionBot/bot/utils/errorable_command.py", line 41, in wrapper
    exception_id = f'{message.message_thread_id}-{message.message_id}'
AttributeError: 'CallbackQuery' object has no attribute 'message_thread_id'

**Comment by seel2304** [comment]
The error was in code. Commit https://github.com/BarsTiger/TeleDiffusionBot/pull/13/commits/75f6404e94b75c35fc461d622ac0c64bb2ce361d fixes that problem
