### ISSUE TITLE
Error No dbmeta file and ChatNotFound: chat not found

### ISSUE THREAD

**Issue by demasakbar** [BarsTiger/TeleDiffusionBot#16]
OS : Windows 11
Python : V3.10.9

I tried to run TeleDiffusionBot `python main.py` and gives an error message like this :

```
TELE-DIFFUSION-BOT
All handlers registered
All callbacks registered
Commands registered
Bot will start now
No dbmeta file
Task exception was never retrieved
future: <Task finished name='Task-7' coro=<Dispatcher._process_polling_updates() done, defined at C:\Users\xxxxxxx\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py:407> exception=ChatNotFound('Chat not found')>
Traceback (most recent call last):
  File "C:\Users\xxxxxxx\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "C:\Users\xxxxxxx\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "C:\Users\xxxxxxx\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "C:\Users\xxxxxxx\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
  File "C:\Users\xxxxxxx\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "D:\Path\Bot\Telegram-Bot\Stable-Diffusion\TeleDiffusionBot\bot\handlers\initialize\all_messages.py", line 9, in sync_db_filter
    await pull()
  File "D:\Path\Bot\Telegram-Bot\Stable-Diffusion\TeleDiffusionBot\bot\db\pull_db.py", line 16, in pull
    await db[DBTables.config].write()
  File "D:\Path\Bot\Telegram-Bot\Stable-Diffusion\TeleDiffusionBot\bot\db\db_model.py", line 25, in write
    await bot.edit_message_media(media=InputMediaDocument(InputFile(DB)),
  File "C:\Users\xxxxxxx\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\bot\bot.py", line 3220, in edit_message_media
    result = await self.request(api.Methods.EDIT_MESSAGE_MEDIA, payload, files)
  File "C:\Users\xxxxxxx\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\bot\base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "C:\Users\xxxxxxx\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\bot\api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "C:\Users\xxxxxxx\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\bot\api.py", line 115, in check_result
    exceptions.BadRequest.detect(description)
  File "C:\Users\xxxxxxx\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\utils\exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.ChatNotFound: Chat not found
```
My directory tree (root folder)
```
[Folder] bot
[Folder] venv
[File] .env
[File] .gitignore
[File] .replit
[File] db
[File] dbmeta
[File] main.py
[File] README.MD
[File] replit.nix
[File] requirements.txt
[File] sync
```

I have also do the privacy setting `/setprivacy` from `ENABLED` to `DISABLED`. 

What do you think what i am wrong?

**Comment by BarsTiger** [comment]
I think, chat id in `.env` is wrong

**Comment by demasakbar** [comment]
> I think, chat id in `.env` is wrong 

`ADMIN` or `DB_CHAT`

**Comment by demasakbar** [comment]
I have already done the following steps:

**Comment by demasakbar** [comment]
I have already done the following steps:
1. Creating a Bot Via @BotFather
2. From the results of making bots with @BotFather obtained `TOKEN`. `TOKEN` from @BotFather copied into the `TOKEN=` line in the `.ENV` file
3. After that I joined the @userinfobot bot. Sent a message `/started` in the bot and got an ID. I copied the ID into the `ADMIN=` line in the `.ENV` file.
4. After that I created a new group, called Raw Group, adding member @RawDataBot to the group. After that, I sent a message in my group (Raw Group). I retrieved the data according to the tutorial on this github `"chat": { "id": -7148xxxxx, ....}`. I input the ID into the `DB_CHAT` row in the `.ENV` row.
5. For `DB_PATH` i fill with `.` (dot).
6. For `ENCRYPTION_KEY` i fill with my password
7. For `ARCHIVE_CHAT` i fill BLANK

is there still something missing?

**Comment by BarsTiger** [comment]
My `.env` looks like this:
```
TOKEN='11110000:SOMETOKEN'
ADMIN='111111111'
DB_CHAT='-111111111'
DB_PATH='.'
ENCRYPTION_KEY='SomeEncryptionKey'
```
Check if yours also

**Comment by demasakbar** [comment]
> My `.env` looks like this:
> ```
> TOKEN='11110000:SOMETOKEN'
> ADMIN='111111111'
> DB_CHAT='-111111111'
> DB_PATH='.'
> ENCRYPTION_KEY='SomeEncryptionKey'
> ```
> Check if yours also

I have fill like this. But still the error. 
For the encryption key, is it filled in whatever? Or how?

**Comment by demasakbar** [comment]
It finally worked. Apparently, we have to put the **bot (created in botfather)** into the group and make it an **admin**. After that in the group we send a message again to get a **new chat id**
