### ISSUE TITLE
starts - but crashes. No dbmeta file

### ISSUE THREAD

**Issue by johndpope** [BarsTiger/TeleDiffusionBot#2]
python main.py                 
TELE-DIFFUSION-BOT
All handlers registered
All callbacks registered
Commands registered
Bot will start now
**No dbmeta file**
Task exception was never retrieved
future: <Task finished name='Task-22' coro=<Dispatcher._process_polling_updates() done, defined at /home/oem/miniconda3/envs/bot/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=ChatNotFound('Chat not found')>
Traceback (most recent call last):
  File "/home/oem/miniconda3/envs/bot/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oem/miniconda3/envs/bot/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oem/miniconda3/envs/bot/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oem/miniconda3/envs/bot/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oem/miniconda3/envs/bot/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oem/Documents/gitWorkspace/TeleDiffusionBot/bot/handlers/initialize/all_messages.py", line 9, in sync_db_filter
    await pull()
  File "/home/oem/Documents/gitWorkspace/TeleDiffusionBot/bot/db/pull_db.py", line 16, in pull
    await db[DBTables.config].write()
  File "/home/oem/Documents/gitWorkspace/TeleDiffusionBot/bot/db/db_model.py", line 25, in write
    await bot.edit_message_media(media=InputMediaDocument(InputFile(DB)),
  File "/home/oem/miniconda3/envs/bot/lib/python3.11/site-packages/aiogram/bot/bot.py", line 3220, in edit_message_media
    result = await self.request(api.Methods.EDIT_MESSAGE_MEDIA, payload, files)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oem/miniconda3/envs/bot/lib/python3.11/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oem/miniconda3/envs/bot/lib/python3.11/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oem/miniconda3/envs/bot/lib/python3.11/site-packages/aiogram/bot/api.py", line 115, in check_result
    exceptions.BadRequest.detect(description)
  File "/home/oem/miniconda3/envs/bot/lib/python3.11/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.ChatNotFound: Chat not found

**Comment by johndpope** [comment]
I see both files there in directory.

**Comment by johndpope** [comment]
I think making bot an admin in group or changing privacy setting is necessary here.

```

Sequence within a BotFather chat:

You: /setprivacy

BotFather: Choose a bot to change group messages settings.

You: @your_name_bot

BotFather: 'Enable' - your bot will only receive messages that either start with the '/' symbol or mention the bot by username.

'Disable' - your bot will receive all messages that people send to groups.

Current status is: ENABLED

You: Disable

BotFather: Success! The new status is: DISABLED. /help
```
https://stackoverflow.com/questions/38565952/how-to-receive-messages-in-group-chats-using-telegram-bot-api/56078309#56078309

**Comment by BarsTiger** [comment]
Thanks! :)
