### ISSUE TITLE
Can't start up main.py

### ISSUE THREAD

**Issue by P1agueDoc** [BarsTiger/TeleDiffusionBot#22]
Traceback (most recent call last):
  File "C:\Users\D0cpl\TeleDiffusionBot\main.py", line 1, in <module>
    from bot.config import BARS_APP_ID
  File "C:\Users\D0cpl\TeleDiffusionBot\bot\config.py", line 7, in <module>
    ADMIN = int(os.getenv('ADMIN'))
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

**Comment by P1agueDoc** [comment]
Problem solved. Just enter pip install aiogram==2.25.2 and after that can python main.py
