### ISSUE TITLE
Generation error

### ISSUE THREAD

**Issue by vasmarfas** [BarsTiger/TeleDiffusionBot#9]
Ubuntu Server 22.04
python 3.10.9

Hello! I have the same problem as it this issue -> https://github.com/BarsTiger/TeleDiffusionBot/issues/3

Steps: 
1) (terminal) python main.py
output (terminal):
TELE-DIFFUSION-BOT
All handlers registered
All callbacks registered
Commands registered
Bot will start now

2) (private telegram chat to bot) /start
output (telegram):
🔄️ Bot database synchronised because of restart. If you tried to run a command, run it again
output (terminal):
First database pulling for this instance - DB is up-to-date
Task exception was never retrieved
future: <Task finished name='Task-11' coro=<Dispatcher._process_polling_updates() done, defined at /media/bad-hdd-nextcloud/nextcloud-data/Programms/TeleDiffusionBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=TypeError('token must be bytes or str')>
Traceback (most recent call last):
  File "/media/bad-hdd-nextcloud/nextcloud-data/Programms/TeleDiffusionBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/media/bad-hdd-nextcloud/nextcloud-data/Programms/TeleDiffusionBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "/media/bad-hdd-nextcloud/nextcloud-data/Programms/TeleDiffusionBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/media/bad-hdd-nextcloud/nextcloud-data/Programms/TeleDiffusionBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
  File "/media/bad-hdd-nextcloud/nextcloud-data/Programms/TeleDiffusionBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/media/bad-hdd-nextcloud/nextcloud-data/Programms/TeleDiffusionBot/bot/handlers/initialize/all_messages.py", line 13, in sync_db_filter
    if not await ping():
  File "/media/bad-hdd-nextcloud/nextcloud-data/Programms/TeleDiffusionBot/bot/modules/api/ping.py", line 6, in ping
    endpoint = decrypt(db[DBTables.config].get('endpoint'))
  File "/media/bad-hdd-nextcloud/nextcloud-data/Programms/TeleDiffusionBot/bot/db/encryption.py", line 25, in decrypt
    return fernet.decrypt(s).decode()
  File "/media/bad-hdd-nextcloud/nextcloud-data/Programms/TeleDiffusionBot/venv/lib/python3.10/site-packages/cryptography/fernet.py", line 85, in decrypt
    timestamp, data = Fernet._get_unverified_token_data(token)
  File "/media/bad-hdd-nextcloud/nextcloud-data/Programms/TeleDiffusionBot/venv/lib/python3.10/site-packages/cryptography/fernet.py", line 113, in _get_unverified_token_data
    raise TypeError("token must be bytes or str")
TypeError: token must be bytes or str

3) (private telegram chat to bot) /setendpoint http://0.0.0.0:7860
output (telegram): none
output (terminal):
Task exception was never retrieved
future: <Task finished name='Task-20' coro=<Dispatcher._process_polling_updates() done, defined at /media/bad-hdd-nextcloud/nextcloud-data/Programms/TeleDiffusionBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=TypeError("argument of type 'NoneType' is not iterable")>
Traceback (most recent call last):
  File "/media/bad-hdd-nextcloud/nextcloud-data/Programms/TeleDiffusionBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/media/bad-hdd-nextcloud/nextcloud-data/Programms/TeleDiffusionBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "/media/bad-hdd-nextcloud/nextcloud-data/Programms/TeleDiffusionBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/media/bad-hdd-nextcloud/nextcloud-data/Programms/TeleDiffusionBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
  File "/media/bad-hdd-nextcloud/nextcloud-data/Programms/TeleDiffusionBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/media/bad-hdd-nextcloud/nextcloud-data/Programms/TeleDiffusionBot/bot/handlers/admin/aliases.py", line 10, in set_endpoint
    if message.from_id not in db[DBTables.config].get('admins') and message.from_id != ADMIN:
TypeError: argument of type 'NoneType' is not iterable

4) (private telegram chat to bot) /generate
output (telegram): 
❌ Error! Report it to admins: 
🐊 /bot/utils/errorable_command.py:42 
😍 KeyError 
👉 KeyError: 'enabled' 

⬇️ Trace: 
🤯 errorable_command.py:22 (in wrapper call)
    _ = await func(*args, **kwargs)
🤯 txt2img.py:17 (in generate_command call)
    if not db[DBTables.config]['enabled']:
🤯 sqlitedict.py:305 (in __getitem__ call)
    raise KeyError(key)
KeyError: 'enabled'
output (terminal): none

What i should to do, to make this bot working?

**Comment by BarsTiger** [comment]
Please, share your .env file (but remove sensitive data such as token, etc., before)

**Comment by BarsTiger** [comment]
Also, endpoint 0.0.0.0 is just alias for accessing it from local devices. When you use 0.0.0.0 as host, access site from `localhost` or `127.0.0.1`. So, try using `/setendpoint http://localhost:7860`

**Comment by BarsTiger** [comment]
Hmmm, re-read your error, I think problem is in `ENCRYPTION_KEY` value in .env. Maybe, you used some special symbols in it, (unexpected behaviour), or even didn't fill it. Fill your `.env` file properly to get it working

**Comment by seel2304** [comment]
My .env file:
TOKEN='0000:XXXX'
ADMIN='000000'
DB_CHAT='-0000'
DB_PATH='.'
ENCRYPTION_KEY= test
END_POINT='http://0.0.0.0:7860'

**Comment by seel2304** [comment]
I tested ENCRYPTION_KEY= 'test' with no effect

**Comment by seel2304** [comment]
I just tried after restarting the bot type in Telegram "/start" double time and it works.. But in terminal still TypeError: token must be bytes or str

**Comment by seel2304** [comment]
I just downloaded this repo to my Windows system, and here the same problem
![image](https://user-images.githubusercontent.com/37144504/235732101-0f43c017-0555-4c35-866c-8b7dcd002e64.png)
![image](https://user-images.githubusercontent.com/37144504/235732174-3c5024c2-5f7c-48d2-a28c-6dec5d37d185.png)

**Comment by BarsTiger** [comment]
![image](https://user-images.githubusercontent.com/60313248/236443321-f65c3da2-013f-49bb-a7ca-98dc63770cf1.png)
This is my `.env`. Try using longer `ENCRYPTION_KEY` (maybe it works?), also set endpoint from command, not from `.env`. 
Try again:
- set up bot like in readme
- change `ENCRYPTION_KEY` to something looong
- run `/start` from admin account
- run `/setendpoint http://localhost:7860`

**Comment by latuyenliet** [comment]
![image](https://github.com/BarsTiger/TeleDiffusionBot/assets/133096323/6daf62bc-3431-4b1b-bbf2-efc88fbaa35f)

still persist 

![image](https://github.com/BarsTiger/TeleDiffusionBot/assets/133096323/d361b5bf-d1c4-4cd6-bf80-3a7ed54e3c46)

**Comment by MastaDan9** [comment]
❌ Error! Report it to admins: 
🐊 \bot\utils\errorable_command.py:42 
😍 KeyError 
👉 KeyError: 'enabled' 

⬇️ Trace: 
🤯 errorable_command.py:22 (in wrapper call)
    _ = await func(*args, **kwargs)
🤯 txt2img.py:19 (in generate_command call)
    if not db[DBTables.config]['enabled']:
🤯 sqlitedict.py:305 (in __getitem__ call)
    raise KeyError(key)
KeyError: 'enabled'

**Comment by BarsTiger** [comment]
Fixed it with latest commit. Reopen issue if it breaks
